### ISSUE TITLE
Scrapman does not exit after request

### ISSUE THREAD

**Issue by kirchnch** [danielnieto/scrapman#4]
Scrapman appears to hang after making requests on Ubuntu 16.04.  Checking the processes (`ps aux | grep electron`), electron still remains running (see picture below).  Sending a SIGTERM to electron processes exits the scrapman script (`killall electron`).  Please let me know if you need anymore info.

[Scrapman.js.txt](https://github.com/danielnieto/scrapman/files/737047/Scrapman.js.txt)

![selection_002](https://cloud.githubusercontent.com/assets/16585910/22398559/cc4fd81c-e53f-11e6-8e6c-7eb236de1a7d.png)

**Comment by danielnieto** [comment]
This is by design. Remember the premise of Scrapman being the fastest it can be? Following this goal, whenever the NPM package is required for the first time it will fire up a single Electron instance (imagine a Chrome instance in the background) so, whenever you need to scrap a website, you call `load` function on the NPM package which then will communicate to the already fired up electron instance to get the html from the page, this is what differentiates Scrapman from Nightmare, scrapman always has a "ready" electron instance with an invisible window ready to load parallel webpages through `webview`s tags added (and later removed) dynamically to it. Whenever you quit the process that is using the Scrapman NPM package, it will automatically kill the electron process, here's the code that performs the killing (from [index.js](https://github.com/danielnieto/scrapman/blob/master/index.js#L29-L38))

```javascript

let killChild = ()=>{ child.kill("SIGINT");}

// when parent process is exiting, then also kill the child process
process.on('exit', killChild);
process.on('SIGINT', killChild);
process.on('SIGTERM', killChild);
process.on('SIGQUIT', killChild);
process.on('SIGHUP', killChild);
process.on('SIGBREAK', killChild);
```

**Comment by kirchnch** [comment]
Right on.  That makes sense.  It may be handy to have convenience functions for initiating or shutting down the electron instance (e.g. start() or close()) to control resources within the script.  Perhaps that can be a pull request if you think that would be suitable and when I get some time.
